GET {{HOST}}/api/auth/secret

### 

POST {{HOST}}/api/auth/register
Content-Type: application/x-www-form-urlencoded

username=subordinate1
&password=Password
&name=Subordinate 1

### 

POST {{HOST}}/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin
&password=
# &password=Password

### 

GET  {{HOST}}/api/auth/user
Authorization: {{TOKEN}}

### 

POST {{HOST}}/api/auth/upload
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="name"

hello world
--Boundary
Content-Disposition: form-data; name="file"; filename="kucing-rumahan-unsplash-768x512.jpeg"
Content-Type: image/jpeg

< C:/Users/fys/Downloads/kucing-rumahan-unsplash-768x512.jpeg
--Boundary--

###
