GET  {{HOST}}/api/auth/user
Authorization: {{TOKEN}}

###

GET {{HOST}}/api/user
        ?page=
        &limit=10
        &keyword=
        &orderBy=id
        &sortedBy=asc
Authorization: {{TOKEN}}

###

GET {{HOST}}/api/user/gp8yQ0v2xR
Authorization: {{TOKEN}}

###

PUT  {{HOST}}/api/user/ZeRAdzy4jJ
Authorization: {{TOKEN}}
Content-Type: application/x-www-form-urlencoded

name=test1

###